# Generated by Django 3.0.2 on 2020-02-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews_ml_models', '0002_dictentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlChecker', models.TextField()),
                ('trustedLabel', models.IntegerField()),
            ],
        ),
    ]
